// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the NativeFileDocuments module

	/**
	* Number of log files on the device to keep, zero or negative means no cleanup
	*/
	public static java.lang.Long getDEVICE_LOG_FILE_RETENTION()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("NativeFileDocuments.DEVICE_LOG_FILE_RETENTION");
	}

	/**
	* Log retention in days, zero or negative means no cleanup
	*/
	public static java.lang.Long getLOG_RETENTION()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("NativeFileDocuments.LOG_RETENTION");
	}

	public static java.lang.String getLOGNODE_NATIVE_FILE_DOCUMENTS()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NativeFileDocuments.LOGNODE_NATIVE_FILE_DOCUMENTS");
	}
}