// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativefiledocuments.proxies;

public class ResizedImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestNativeFileDocuments.ResizedImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageWidth("ImageWidth"),
		ImageHeight("ImageHeight"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ResizedImage_ImageToResize("TestNativeFileDocuments.ResizedImage_ImageToResize");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResizedImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResizedImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resizedImageMendixObject)
	{
		super(context, resizedImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, resizedImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'ResizedImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testnativefiledocuments.proxies.ResizedImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testnativefiledocuments.proxies.ResizedImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testnativefiledocuments.proxies.ResizedImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testnativefiledocuments.proxies.ResizedImage(context, mendixObject);
	}

	public static testnativefiledocuments.proxies.ResizedImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testnativefiledocuments.proxies.ResizedImage.initialize(context, mendixObject);
	}

	public static java.util.List<testnativefiledocuments.proxies.ResizedImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testnativefiledocuments.proxies.ResizedImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ImageWidth
	 */
	public final java.lang.Integer getImageWidth()
	{
		return getImageWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageWidth
	 */
	public final java.lang.Integer getImageWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ImageWidth.toString());
	}

	/**
	 * Set value of ImageWidth
	 * @param imagewidth
	 */
	public final void setImageWidth(java.lang.Integer imagewidth)
	{
		setImageWidth(getContext(), imagewidth);
	}

	/**
	 * Set value of ImageWidth
	 * @param context
	 * @param imagewidth
	 */
	public final void setImageWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer imagewidth)
	{
		getMendixObject().setValue(context, MemberNames.ImageWidth.toString(), imagewidth);
	}

	/**
	 * @return value of ImageHeight
	 */
	public final java.lang.Integer getImageHeight()
	{
		return getImageHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageHeight
	 */
	public final java.lang.Integer getImageHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ImageHeight.toString());
	}

	/**
	 * Set value of ImageHeight
	 * @param imageheight
	 */
	public final void setImageHeight(java.lang.Integer imageheight)
	{
		setImageHeight(getContext(), imageheight);
	}

	/**
	 * Set value of ImageHeight
	 * @param context
	 * @param imageheight
	 */
	public final void setImageHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer imageheight)
	{
		getMendixObject().setValue(context, MemberNames.ImageHeight.toString(), imageheight);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResizedImage_ImageToResize
	 */
	public final testnativefiledocuments.proxies.ImageToResize getResizedImage_ImageToResize() throws com.mendix.core.CoreException
	{
		return getResizedImage_ImageToResize(getContext());
	}

	/**
	 * @param context
	 * @return value of ResizedImage_ImageToResize
	 * @throws com.mendix.core.CoreException
	 */
	public final testnativefiledocuments.proxies.ImageToResize getResizedImage_ImageToResize(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testnativefiledocuments.proxies.ImageToResize result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResizedImage_ImageToResize.toString());
		if (identifier != null) {
			result = testnativefiledocuments.proxies.ImageToResize.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResizedImage_ImageToResize
	 * @param resizedimage_imagetoresize
	 */
	public final void setResizedImage_ImageToResize(testnativefiledocuments.proxies.ImageToResize resizedimage_imagetoresize)
	{
		setResizedImage_ImageToResize(getContext(), resizedimage_imagetoresize);
	}

	/**
	 * Set value of ResizedImage_ImageToResize
	 * @param context
	 * @param resizedimage_imagetoresize
	 */
	public final void setResizedImage_ImageToResize(com.mendix.systemwideinterfaces.core.IContext context, testnativefiledocuments.proxies.ImageToResize resizedimage_imagetoresize)
	{
		if (resizedimage_imagetoresize == null) {
			getMendixObject().setValue(context, MemberNames.ResizedImage_ImageToResize.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResizedImage_ImageToResize.toString(), resizedimage_imagetoresize.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testnativefiledocuments.proxies.ResizedImage that = (testnativefiledocuments.proxies.ResizedImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
