// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativefiledocuments.proxies;

public class TestWriteFileResult extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestNativeFileDocuments.TestWriteFileResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		TestWriteFileResult_TestWriteFile("TestNativeFileDocuments.TestWriteFileResult_TestWriteFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestWriteFileResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestWriteFileResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testWriteFileResultMendixObject)
	{
		super(context, testWriteFileResultMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, testWriteFileResultMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'TestWriteFileResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testnativefiledocuments.proxies.TestWriteFileResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testnativefiledocuments.proxies.TestWriteFileResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testnativefiledocuments.proxies.TestWriteFileResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testnativefiledocuments.proxies.TestWriteFileResult(context, mendixObject);
	}

	public static testnativefiledocuments.proxies.TestWriteFileResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testnativefiledocuments.proxies.TestWriteFileResult.initialize(context, mendixObject);
	}

	public static java.util.List<testnativefiledocuments.proxies.TestWriteFileResult> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testnativefiledocuments.proxies.TestWriteFileResult.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestWriteFileResult_TestWriteFile
	 */
	public final testnativefiledocuments.proxies.TestWriteFile getTestWriteFileResult_TestWriteFile() throws com.mendix.core.CoreException
	{
		return getTestWriteFileResult_TestWriteFile(getContext());
	}

	/**
	 * @param context
	 * @return value of TestWriteFileResult_TestWriteFile
	 * @throws com.mendix.core.CoreException
	 */
	public final testnativefiledocuments.proxies.TestWriteFile getTestWriteFileResult_TestWriteFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testnativefiledocuments.proxies.TestWriteFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestWriteFileResult_TestWriteFile.toString());
		if (identifier != null) {
			result = testnativefiledocuments.proxies.TestWriteFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestWriteFileResult_TestWriteFile
	 * @param testwritefileresult_testwritefile
	 */
	public final void setTestWriteFileResult_TestWriteFile(testnativefiledocuments.proxies.TestWriteFile testwritefileresult_testwritefile)
	{
		setTestWriteFileResult_TestWriteFile(getContext(), testwritefileresult_testwritefile);
	}

	/**
	 * Set value of TestWriteFileResult_TestWriteFile
	 * @param context
	 * @param testwritefileresult_testwritefile
	 */
	public final void setTestWriteFileResult_TestWriteFile(com.mendix.systemwideinterfaces.core.IContext context, testnativefiledocuments.proxies.TestWriteFile testwritefileresult_testwritefile)
	{
		if (testwritefileresult_testwritefile == null) {
			getMendixObject().setValue(context, MemberNames.TestWriteFileResult_TestWriteFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestWriteFileResult_TestWriteFile.toString(), testwritefileresult_testwritefile.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testnativefiledocuments.proxies.TestWriteFileResult that = (testnativefiledocuments.proxies.TestWriteFileResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
