// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativefiledocuments.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the TestNativeFileDocuments module
	public static void aCT_ImageToResize_Save(IContext context, testnativefiledocuments.proxies.ImageToResize _testImageToResize)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestImageToResize", _testImageToResize == null ? null : _testImageToResize.getMendixObject());
		Core.microflowCall("TestNativeFileDocuments.ACT_ImageToResize_Save").withParams(params).execute(context);
	}
	public static void aCT_TestCropImage_Save(IContext context, testnativefiledocuments.proxies.TestCropImage _testCropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestCropImage", _testCropImage == null ? null : _testCropImage.getMendixObject());
		Core.microflowCall("TestNativeFileDocuments.ACT_TestCropImage_Save").withParams(params).execute(context);
	}
	public static void aCT_TestDocument_Save(IContext context, testnativefiledocuments.proxies.TestDocument _testDocument)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestDocument", _testDocument == null ? null : _testDocument.getMendixObject());
		Core.microflowCall("TestNativeFileDocuments.ACT_TestDocument_Save").withParams(params).execute(context);
	}
	public static void aCT_TestWriteFile_Save(IContext context, testnativefiledocuments.proxies.TestWriteFile _testWriteFile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestWriteFile", _testWriteFile == null ? null : _testWriteFile.getMendixObject());
		Core.microflowCall("TestNativeFileDocuments.ACT_TestWriteFile_Save").withParams(params).execute(context);
	}
	public static void aCT_TestWriteFileResult_Download(IContext context, testnativefiledocuments.proxies.TestWriteFileResult _testWriteFileResult)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestWriteFileResult", _testWriteFileResult == null ? null : _testWriteFileResult.getMendixObject());
		Core.microflowCall("TestNativeFileDocuments.ACT_TestWriteFileResult_Download").withParams(params).execute(context);
	}
}
