// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the TestModule module
	public static void aCT_TestImage_Save(IContext context, testmodule.proxies.TestImage _testImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestImage", _testImage == null ? null : _testImage.getMendixObject());
		Core.microflowCall("TestModule.ACT_TestImage_Save").withParams(params).execute(context);
	}
}