// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum DocumentType
{
	audio(new java.lang.String[][] { new java.lang.String[] { "en_US", "audio" } }),
	csv(new java.lang.String[][] { new java.lang.String[] { "en_US", "csv" } }),
	doc(new java.lang.String[][] { new java.lang.String[] { "en_US", "doc" } }),
	docx(new java.lang.String[][] { new java.lang.String[] { "en_US", "docx" } }),
	pdf(new java.lang.String[][] { new java.lang.String[] { "en_US", "pdf" } }),
	plainText(new java.lang.String[][] { new java.lang.String[] { "en_US", "plainText" } }),
	ppt(new java.lang.String[][] { new java.lang.String[] { "en_US", "ppt" } }),
	pptx(new java.lang.String[][] { new java.lang.String[] { "en_US", "pptx" } }),
	video(new java.lang.String[][] { new java.lang.String[] { "en_US", "video" } }),
	xls(new java.lang.String[][] { new java.lang.String[] { "en_US", "xls" } }),
	xlsx(new java.lang.String[][] { new java.lang.String[] { "en_US", "xlsx" } }),
	zip(new java.lang.String[][] { new java.lang.String[] { "en_US", "zip" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private DocumentType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
