// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public class ImageCropMetaData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject imageCropMetaDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeFileDocuments.ImageCropMetaData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageCropped("ImageCropped"),
		CroppedImageFullPath("CroppedImageFullPath"),
		CroppedWidth("CroppedWidth"),
		CroppedHeight("CroppedHeight"),
		CroppedSize("CroppedSize");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImageCropMetaData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ImageCropMetaData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject imageCropMetaDataMendixObject)
	{
		if (imageCropMetaDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, imageCropMetaDataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.imageCropMetaDataMendixObject = imageCropMetaDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ImageCropMetaData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nativefiledocuments.proxies.ImageCropMetaData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nativefiledocuments.proxies.ImageCropMetaData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativefiledocuments.proxies.ImageCropMetaData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativefiledocuments.proxies.ImageCropMetaData(context, mendixObject);
	}

	public static nativefiledocuments.proxies.ImageCropMetaData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativefiledocuments.proxies.ImageCropMetaData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ImageCropped
	 */
	public final java.lang.Boolean getImageCropped()
	{
		return getImageCropped(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageCropped
	 */
	public final java.lang.Boolean getImageCropped(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImageCropped.toString());
	}

	/**
	 * Set value of ImageCropped
	 * @param imagecropped
	 */
	public final void setImageCropped(java.lang.Boolean imagecropped)
	{
		setImageCropped(getContext(), imagecropped);
	}

	/**
	 * Set value of ImageCropped
	 * @param context
	 * @param imagecropped
	 */
	public final void setImageCropped(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean imagecropped)
	{
		getMendixObject().setValue(context, MemberNames.ImageCropped.toString(), imagecropped);
	}

	/**
	 * @return value of CroppedImageFullPath
	 */
	public final java.lang.String getCroppedImageFullPath()
	{
		return getCroppedImageFullPath(getContext());
	}

	/**
	 * @param context
	 * @return value of CroppedImageFullPath
	 */
	public final java.lang.String getCroppedImageFullPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CroppedImageFullPath.toString());
	}

	/**
	 * Set value of CroppedImageFullPath
	 * @param croppedimagefullpath
	 */
	public final void setCroppedImageFullPath(java.lang.String croppedimagefullpath)
	{
		setCroppedImageFullPath(getContext(), croppedimagefullpath);
	}

	/**
	 * Set value of CroppedImageFullPath
	 * @param context
	 * @param croppedimagefullpath
	 */
	public final void setCroppedImageFullPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String croppedimagefullpath)
	{
		getMendixObject().setValue(context, MemberNames.CroppedImageFullPath.toString(), croppedimagefullpath);
	}

	/**
	 * @return value of CroppedWidth
	 */
	public final java.lang.Integer getCroppedWidth()
	{
		return getCroppedWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of CroppedWidth
	 */
	public final java.lang.Integer getCroppedWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CroppedWidth.toString());
	}

	/**
	 * Set value of CroppedWidth
	 * @param croppedwidth
	 */
	public final void setCroppedWidth(java.lang.Integer croppedwidth)
	{
		setCroppedWidth(getContext(), croppedwidth);
	}

	/**
	 * Set value of CroppedWidth
	 * @param context
	 * @param croppedwidth
	 */
	public final void setCroppedWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer croppedwidth)
	{
		getMendixObject().setValue(context, MemberNames.CroppedWidth.toString(), croppedwidth);
	}

	/**
	 * @return value of CroppedHeight
	 */
	public final java.lang.Integer getCroppedHeight()
	{
		return getCroppedHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of CroppedHeight
	 */
	public final java.lang.Integer getCroppedHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CroppedHeight.toString());
	}

	/**
	 * Set value of CroppedHeight
	 * @param croppedheight
	 */
	public final void setCroppedHeight(java.lang.Integer croppedheight)
	{
		setCroppedHeight(getContext(), croppedheight);
	}

	/**
	 * Set value of CroppedHeight
	 * @param context
	 * @param croppedheight
	 */
	public final void setCroppedHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer croppedheight)
	{
		getMendixObject().setValue(context, MemberNames.CroppedHeight.toString(), croppedheight);
	}

	/**
	 * @return value of CroppedSize
	 */
	public final java.lang.Integer getCroppedSize()
	{
		return getCroppedSize(getContext());
	}

	/**
	 * @param context
	 * @return value of CroppedSize
	 */
	public final java.lang.Integer getCroppedSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CroppedSize.toString());
	}

	/**
	 * Set value of CroppedSize
	 * @param croppedsize
	 */
	public final void setCroppedSize(java.lang.Integer croppedsize)
	{
		setCroppedSize(getContext(), croppedsize);
	}

	/**
	 * Set value of CroppedSize
	 * @param context
	 * @param croppedsize
	 */
	public final void setCroppedSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer croppedsize)
	{
		getMendixObject().setValue(context, MemberNames.CroppedSize.toString(), croppedsize);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return imageCropMetaDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativefiledocuments.proxies.ImageCropMetaData that = (nativefiledocuments.proxies.ImageCropMetaData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
