// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum ShareToType
{
	email(new java.lang.String[][] { new java.lang.String[] { "en_US", "Email" }, new java.lang.String[] { "nl_NL", "Email" } }),
	facebook(new java.lang.String[][] { new java.lang.String[] { "en_US", "Facebook" }, new java.lang.String[] { "nl_NL", "Facebook" } }),
	instagram(new java.lang.String[][] { new java.lang.String[] { "en_US", "Instagram" }, new java.lang.String[] { "nl_NL", "Instagram" } }),
	linkedin(new java.lang.String[][] { new java.lang.String[] { "en_US", "Linkedin" }, new java.lang.String[] { "nl_NL", "Linkedin" } }),
	pinterest(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pinterest" }, new java.lang.String[] { "nl_NL", "Pinterest" } }),
	SMS(new java.lang.String[][] { new java.lang.String[] { "en_US", "SMS" }, new java.lang.String[] { "nl_NL", "SMS" } }),
	twitter(new java.lang.String[][] { new java.lang.String[] { "en_US", "Twitter" }, new java.lang.String[] { "nl_NL", "Twitter" } }),
	whatsapp(new java.lang.String[][] { new java.lang.String[] { "en_US", "Whatsapp" }, new java.lang.String[] { "nl_NL", "Whatsapp" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ShareToType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
